# Generated by Django 3.2 on 2021-04-22 21:55

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=True, max_length=65)),
                ('course_number', models.IntegerField(default=True, max_length=50)),
                ('instructor', models.CharField(default=True, max_length=65)),
                ('duration', models.FloatField(default=True, max_length=50)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
