# Generated by Django 3.2 on 2021-04-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0002_alter_djangoclasses_course_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='course_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='duration',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='instructor',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='title',
            field=models.CharField(max_length=65),
        ),
    ]
